"""Investor-grade Markdown report generator.

v1.6.1 P.9: extracted from ``flowsheet_service.py``. Re-exported from
the facade for back-compat.
"""

from __future__ import annotations

import datetime
import math
from typing import List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from pse_ecosystem.ui.flowsheet_service import (
        ProjectEconomicsConfig,
        SafetyMarginRow,
    )

from pse_ecosystem.ui.economics_bridge import compute_project_economics
from pse_ecosystem.ui.sensitivity_analysis import TornadoRow


def _extract_econ_kpi(rows, metric):
    """Local copy — keeps the report module self-sufficient."""
    for r in rows:
        if r.get("Metric") == metric:
            try:
                return float(r["Value"])
            except (TypeError, ValueError):
                return float("nan")
    return float("nan")


# ── Investor Report generator (v1.5.1) ───────────────────────────────────────

def generate_investor_report(
    flowsheet,
    result,
    econ_config: "ProjectEconomicsConfig",
    safety_rows: Optional[List["SafetyMarginRow"]] = None,
    template_spec=None,
    scenario_label: str = "Base Case",
    tornado_rows: Optional[List[TornadoRow]] = None,
) -> str:
    """Generate an investor-grade Markdown summary report.

    Produces a structured Markdown document suitable for:
    - Internal investment committee review
    - Preliminary due diligence package
    - Grant application technical annex

    All assumptions are explicitly listed so the document is self-contained and
    auditable.  Suitable for download via ``st.download_button(mime="text/markdown")``.

    Parameters
    ----------
    flowsheet      : Solved ``BaseFlowsheet``.
    result         : ``SolveResult`` from the Orchestrator.
    econ_config    : ``ProjectEconomicsConfig`` used for the solve.
    safety_rows    : Output of ``compute_safety_margins()``.
    template_spec  : ``TemplateSpec`` for the selected template (display name, description).
    scenario_label : Name of this scenario (e.g., "Base Case", "Optimistic").
    tornado_rows   : Pre-computed tornado sensitivity (top-5 shown).

    Returns
    -------
    str — Markdown document.
    """
    import datetime, math

    today = datetime.date.today().isoformat()
    plant_name = getattr(template_spec, "display_name", "Process Plant") if template_spec else "Process Plant"
    plant_desc = getattr(template_spec, "description", "") if template_spec else ""
    status_str = "CONVERGED" if result.converged else f"NOT CONVERGED ({result.message})"

    lines: List[str] = []

    # ── Cover ────────────────────────────────────────────────────────────────
    lines += [
        f"# Investment Summary — {plant_name}",
        f"**Scenario:** {scenario_label}  |  **Date:** {today}  |  "
        f"**Status:** {status_str}  |  "
        f"**Solver iterations:** {result.iterations}",
        "",
        "> *Generated by PSE Ecosystem v1.5.1.  "
        "This report contains preliminary steady-state simulation results.  "
        "All assumptions are listed in §6.  "
        "Not a certified engineering design — engage a qualified process engineer for final design.*",
        "",
    ]

    # ── §1 Process Description ───────────────────────────────────────────────
    lines += [
        "## §1 Process Description",
        "",
        f"**Technology:** {plant_name}",
    ]
    if plant_desc:
        lines += [f"**Summary:** {plant_desc}", ""]

    if flowsheet is not None:
        unit_lines = [f"- `{u.unit_id}` ({type(u).__name__})" for u in flowsheet.units]
        lines += ["**Unit inventory:**", ""] + unit_lines + [""]

    # ── §2 Key Performance Indicators ────────────────────────────────────────
    lines += ["## §2 Key Performance Indicators", ""]
    if result.kpis:
        lines += ["| KPI | Value |", "|---|---|"]
        for k, v in result.kpis.items():
            lines.append(f"| {k} | {v:.4g} |")
        lines.append("")

    # ── §3 Project Economics ─────────────────────────────────────────────────
    lines += ["## §3 Project Economics", ""]
    try:
        econ_rows = compute_project_economics(flowsheet, result.x, result.kpis, econ_config)
        _KEY_METRICS = ["Installed CAPEX", "Annual OPEX", "TAC", "LCOH", "LCOE", "NPV", "IRR"]
        lines += ["| Metric | Value | Unit |", "|---|---|---|"]
        for row in econ_rows:
            if row["Metric"] in _KEY_METRICS:
                v = row["Value"]
                v_str = f"{v:,.2f}" if isinstance(v, float) and not math.isnan(v) and not math.isinf(v) else str(v)
                lines.append(f"| {row['Metric']} | {v_str} | {row['Unit']} |")
        lines.append("")

        lcoh = _extract_econ_kpi(econ_rows, "LCOH")
        if not math.isnan(lcoh):
            lines += [
                f"> **Break-even H₂ price = LCOH = ${lcoh:.3f}/kg.**  "
                "The plant is profitable at any H₂ market price above this value.",
                "",
            ]
    except Exception as e:
        lines += [f"*Economics computation failed: {e}*", ""]

    # ── §4 Engineering Safety Assessment ─────────────────────────────────────
    lines += ["## §4 Engineering Safety Assessment", ""]
    if safety_rows:
        lines += [
            "| Unit | Check | Value | Status | Detail |",
            "|---|---|---|---|---|",
        ]
        for row in safety_rows:
            v_str = f"{row.value:.4g}" if row.value == row.value else "—"
            lines.append(f"| {row.unit_id} | {row.check_type} | {v_str} | **{row.status}** | {row.detail} |")
        lines += [
            "",
            "*ASME estimates use default vessel radius unless unit declares `vessel_radius_m`.  "
            "Not a certified ASME pressure vessel calculation.*",
            "",
        ]
    else:
        lines += ["*No pressure-vessel units identified in this flowsheet.*", ""]

    # ── §5 Economic Sensitivity (Tornado) ────────────────────────────────────
    if tornado_rows:
        lines += ["## §5 Economic Sensitivity (Top 5 Drivers)", ""]
        lines += ["| Parameter | −20% Impact | +20% Impact | Swing |", "|---|---|---|---|"]
        for row in tornado_rows[:5]:
            lines.append(
                f"| {row.param_label} | {row.delta_low:+.4g} | {row.delta_high:+.4g} | {row.impact:.4g} |"
            )
        lines.append("")

    # ── §6 Assumptions & Limitations ─────────────────────────────────────────
    lines += [
        "## §6 Assumptions & Limitations",
        "",
        "| Parameter | Value |",
        "|---|---|",
        f"| Plant life | {econ_config.plant_life_yr} yr |",
        f"| Discount rate (WACC) | {econ_config.interest_rate*100:.1f}% |",
        f"| Target CEPCI year | {econ_config.target_year} |",
        f"| Lang factor | {econ_config.lang_factor} |",
        f"| Operating hours | {econ_config.operating_hours_per_year:,.0f} h/yr |",
        f"| Electricity price | ${econ_config.electricity_price_USD_per_kWh:.3f}/kWh |",
        f"| Biomass price | ${econ_config.biomass_price_USD_per_tonne:.1f}/tonne |",
        f"| Carbon tax | ${econ_config.carbon_tax_USD_per_tonne:.1f}/tonne CO₂ |",
        f"| Tax rate | {econ_config.tax_rate*100:.1f}% (informational — pre-tax model) |",
        "",
        "**Model limitations:**",
        "- Steady-state, single-period, deterministic simulation",
        "- Pre-tax DCF (after-tax model reserved for v1.6)",
        "- No revenue term in NPV unless product price is explicitly set",
        "- Equipment costs from SSLW correlations (±30% accuracy)",
        "- ASME sizing uses conservative default geometry where unit params are absent",
        "",
        "---",
        f"*PSE Ecosystem v1.5.1 — Private — University of Surrey — {today}*",
    ]

    return "\n".join(lines)
