"""TVSA (Temperature-Vacuum Swing Adsorption) Direct Air Capture unit.

Linearised DAC model suitable for SLP-based flowsheet optimisation.  All
residual equations are linear in the operating variables (at fixed efficiency
parameters), so ``is_linear=True`` and the SLP driver short-circuits to a
single LP solve.

Physics
-------
Ambient air (≈415 ppm CO₂) is contacted with a solid sorbent that selectively
adsorbs CO₂.  After loading, the sorbent is regenerated by applying heat and
vacuum (TVSA cycle).  Three energy duties are tracked:

    W_fan    = k_fan × F_air          [kW] — fan electricity
    Q_regen  = k_regen × F_CO2_cap    [kW] — thermal desorption duty
    W_vac    = k_vac × F_CO2_cap      [kW] — vacuum pump electricity

where the k coefficients are derived from sorbent properties and cycle
parameters (see ``__init__`` for defaults).

Reference sorbent parameters (APDES-NFC, Fasihi et al. 2022):
    ΔH_des  = 70 kJ/mol CO₂
    T_des   = 120 °C,  P_des = 5 kPa (vacuum swing)
    Fan ΔP  = 200 Pa,  η_fan = 0.75,  η_vac = 0.70
"""

from __future__ import annotations

import math
from typing import Dict, List, Tuple

import numpy as np

from pse_ecosystem.core.contracts import LinearizedModel, PrimalGuess, StreamPort
from pse_ecosystem.models.base_unit import BaseUnit

# Molar mass and density of air
_M_AIR = 0.029       # kg/mol
_RHO_AIR = 1.225     # kg/m³ at STP
_M_CO2 = 0.044       # kg/mol
_R = 8.314e-3        # kJ/(mol·K)

# Ambient CO₂ mole fraction (v1.4.0 audit N5 — also exposed as a per-instance
# parameter on TVSAContactor so the model is not locked to 2015-era ambient
# values; the constant below is now just the constructor default).
_Y_CO2_ATM = 415e-6  # 415 ppm

# Ambient T / P defaults used to pin the air_in port (audit N2). These are
# also the constants used by the analytical Jacobian — the two pin rows are
# linear in T_in / P_in with unit coefficients.
_T_AMB_DEFAULT_K = 298.15
_P_AMB_DEFAULT_kPa = 101.325


class TVSAContactor(BaseUnit):
    """TVSA Direct Air Capture contactor with analytical Jacobian.

    Parameters
    ----------
    unit_id :
        Unique identifier for this unit instance.
    eta_cap :
        CO₂ capture efficiency (fraction of atmospheric CO₂ in the air stream
        that is adsorbed, default 0.85).
    dP_fan_Pa :
        Contactor fan pressure drop [Pa] (default 200).
    eta_fan :
        Fan isentropic efficiency (default 0.75).
    dH_des_kJ_per_mol :
        Sorbent desorption enthalpy [kJ/mol CO₂] (default 70.0).
    T_des_K :
        Desorption (regeneration) temperature [K] (default 393, i.e. 120 °C).
    P_ads_kPa :
        Adsorption (atmospheric) pressure [kPa] (default 101.325).
    P_des_kPa :
        Desorption (vacuum) pressure [kPa] (default 5.0).
    eta_vac :
        Vacuum pump efficiency (default 0.70).
    """

    is_linear: bool = True

    def __init__(
        self,
        unit_id: str,
        *,
        eta_cap: float = 0.85,
        dP_fan_Pa: float = 200.0,
        eta_fan: float = 0.75,
        dH_des_kJ_per_mol: float = 70.0,
        T_des_K: float = 393.0,
        P_ads_kPa: float = 101.325,
        P_des_kPa: float = 5.0,
        eta_vac: float = 0.70,
        y_co2_atm: float = _Y_CO2_ATM,
    ):
        # v1.4.0 audit N5 — atmospheric CO₂ mole fraction was a module
        # constant (415 ppm). Now exposed per-instance with the 2015-era
        # default; pilot DAC studies and point-source contactors can
        # override (350 ppm historical, 420 ppm current ambient, up to
        # 1200 ppm for indoor-air HVAC recirculation loops).
        if not (1e-6 <= y_co2_atm <= 0.05):
            raise ValueError(
                f"TVSAContactor y_co2_atm must be in [1e-6, 0.05] (1 ppm – "
                f"50 000 ppm); got {y_co2_atm:.3e}."
            )
        self.unit_id = unit_id
        self.eta_cap = eta_cap
        self.y_co2_atm = float(y_co2_atm)

        # Derived linear coefficients
        # k_fan [kW per (mol/s) of air]
        self._k_fan = _M_AIR * dP_fan_Pa / (_RHO_AIR * eta_fan * 1000.0)
        # k_regen [kW per (mol/s) of CO2 captured]
        self._k_regen = dH_des_kJ_per_mol
        # k_vac [kW per (mol/s) of CO2 captured]
        self._k_vac = (
            _R * T_des_K * math.log(P_ads_kPa / P_des_kPa) / eta_vac
        )

        # Port definitions
        self.air_in_port = StreamPort(
            unit_id, "air_in",
            components=["Air"],
            has_T=True, has_P=True,
            phase="gas",
            species=frozenset({"Air"}),
        )
        self.co2_out_port = StreamPort(
            unit_id, "co2_out",
            components=["CO2"],
            has_T=False, has_P=False,
            phase="gas",
            species=frozenset({"CO2"}),
        )
        self.depleted_air_out_port = StreamPort(
            unit_id, "depleted_air_out",
            components=["Air"],
            has_T=False, has_P=False,
            phase="gas",
            species=frozenset({"Air"}),
        )

        # Variable name shorthands
        self._v_air = f"{unit_id}.air_in.F_Air"
        self._v_T_in = f"{unit_id}.air_in.T"
        self._v_P_in = f"{unit_id}.air_in.P"
        self._v_co2 = f"{unit_id}.co2_out.F_CO2"
        self._v_dep = f"{unit_id}.depleted_air_out.F_Air"
        self._v_wfan = f"{unit_id}.W_fan_kW"
        self._v_qreg = f"{unit_id}.Q_regen_kW"
        self._v_wvac = f"{unit_id}.W_vac_kW"

        self._capture_rate = eta_cap * self.y_co2_atm  # mol CO2 captured per mol air

    # ── Abstract interface ────────────────────────────────────────────────

    def variables(self) -> List[str]:
        return [
            self._v_air, self._v_T_in, self._v_P_in,
            self._v_co2, self._v_dep,
            self._v_wfan, self._v_qreg, self._v_wvac,
        ]

    def bounds(self) -> Dict[str, Tuple[float, float]]:
        uid = self.unit_id
        return {
            self._v_air:  (0.0, 1e6),    # mol/s — ambient air flow
            self._v_T_in: (270.0, 320.0), # K — near-ambient
            self._v_P_in: (95.0, 105.0),  # kPa — atmospheric
            self._v_co2:  (0.0, 1e4),
            self._v_dep:  (0.0, 1e6),
            self._v_wfan: (0.0, 1e5),
            self._v_qreg: (0.0, 1e6),
            self._v_wvac: (0.0, 1e5),
        }

    def residual(self, x: Dict[str, float]) -> np.ndarray:
        F_air = x.get(self._v_air, 0.0)
        T_in  = x.get(self._v_T_in, _T_AMB_DEFAULT_K)
        P_in  = x.get(self._v_P_in, _P_AMB_DEFAULT_kPa)
        F_co2 = x.get(self._v_co2, 0.0)
        F_dep = x.get(self._v_dep, 0.0)
        W_fan = x.get(self._v_wfan, 0.0)
        Q_reg = x.get(self._v_qreg, 0.0)
        W_vac = x.get(self._v_wvac, 0.0)
        cr = self._capture_rate
        # v1.4.0 audit N2 — T_in and P_in were declared as port variables but
        # never appeared in the residual; the LP picked them arbitrarily
        # inside the (270, 320) K and (95, 105) kPa bounds. Pin them to
        # nominal ambient defaults so the reported value reflects intent.
        # Upstream connections via `BaseFlowsheet.connect()` can still
        # override these via equality constraints (the LP takes the
        # tighter of the two — see `lp_builder.py` per-unit bound merge).
        return np.array([
            F_co2 - cr * F_air,
            F_dep - (1.0 - cr) * F_air,
            W_fan - self._k_fan * F_air,
            Q_reg - self._k_regen * F_co2,
            W_vac - self._k_vac * F_co2,
            T_in  - _T_AMB_DEFAULT_K,
            P_in  - _P_AMB_DEFAULT_kPa,
        ], dtype=float)

    def objective_contribution(self, x: Dict[str, float]) -> Dict[str, float]:
        # OPEX: electricity cost for fan + vacuum pump; heat cost for regen
        # Coefficients are $/kWh defaults — zeroed here so callers set them.
        return {}

    def kpis(self, x: Dict[str, float]) -> Dict[str, float]:
        # v1.4.0 audit N15 — match the residual's near-zero handling. A 1e-9
        # mol/s F_co2 produces a 1e13 kWh/tonne specific-energy nonsense.
        # Use a 1e-6 mol/s floor (≈0.4 mg/h CO₂ — below any realistic
        # pilot DAC unit) so the KPI either reports near-zero throughput
        # or a sensibly-bounded number.
        _FLOOR_MOL_S = 1.0e-6
        F_co2 = max(x.get(self._v_co2, 0.0), _FLOOR_MOL_S)
        W_fan = x.get(self._v_wfan, 0.0)
        Q_reg = x.get(self._v_qreg, 0.0)
        W_vac = x.get(self._v_wvac, 0.0)
        total_power = W_fan + W_vac  # kW electrical
        total_heat = Q_reg           # kW thermal
        # CO2 mass rate [kg/s]
        co2_kg_s = F_co2 * _M_CO2
        co2_tonne_day = co2_kg_s * 86400.0 / 1000.0
        specific_elec = (total_power / co2_kg_s / 3600.0) if F_co2 > _FLOOR_MOL_S * 1.001 else 0.0
        specific_heat = (total_heat / co2_kg_s / 3600.0) if F_co2 > _FLOOR_MOL_S * 1.001 else 0.0
        return {
            "co2_capture_rate_tonne_per_day": co2_tonne_day,
            "specific_elec_kWh_per_tCO2": specific_elec * 1000.0,
            "specific_heat_kWh_per_tCO2": specific_heat * 1000.0,
            "specific_energy_kWh_per_tCO2": (specific_elec + specific_heat) * 1000.0,
            "W_fan_kW": W_fan,
            "Q_regen_kW": Q_reg,
            "W_vac_kW": W_vac,
        }

    def capex(self, x: Dict[str, float]) -> float:
        from pse_ecosystem.models.costing.sslw_costing import vessel_purchase_cost_USD

        F_co2 = max(x.get(self._v_co2, 0.0), 1e-6)
        annual_co2_tonnes = F_co2 * _M_CO2 * 3600.0 * 8000.0 / 1000.0
        # Approximate contactor vessel: ~5 m³ per tonne CO2/yr at 10,000 t/yr scale
        vol_m3 = max(5.0 * annual_co2_tonnes / 10_000.0, 0.01)
        return vessel_purchase_cost_USD(vol_m3, material="SS")

    # ── Analytical linearise (override for performance) ───────────────────

    def linearize(self, guess: PrimalGuess) -> LinearizedModel:
        vnames = self.variables()
        idx = {v: i for i, v in enumerate(vnames)}
        n = len(vnames)
        x0_dict = {v: guess.values.get(v, 0.0) for v in vnames}
        x0 = np.array([x0_dict[v] for v in vnames], dtype=float)
        f0 = self.residual(x0_dict)
        cr = self._capture_rate

        # J[row, col]: 7 residuals × 8 variables (v1.4.0 audit N2 — two extra
        # rows pin T_in / P_in to the ambient defaults).
        J = np.zeros((7, n), dtype=float)
        i_air = idx[self._v_air]
        i_T   = idx[self._v_T_in]
        i_P   = idx[self._v_P_in]
        i_co2 = idx[self._v_co2]
        i_dep = idx[self._v_dep]
        i_wfan = idx[self._v_wfan]
        i_qreg = idx[self._v_qreg]
        i_wvac = idx[self._v_wvac]

        # r0: F_co2 - cr*F_air = 0
        J[0, i_air] = -cr;    J[0, i_co2] = 1.0
        # r1: F_dep - (1-cr)*F_air = 0
        J[1, i_air] = -(1.0 - cr);  J[1, i_dep] = 1.0
        # r2: W_fan - k_fan*F_air = 0
        J[2, i_air] = -self._k_fan;  J[2, i_wfan] = 1.0
        # r3: Q_reg - k_regen*F_co2 = 0
        J[3, i_co2] = -self._k_regen;  J[3, i_qreg] = 1.0
        # r4: W_vac - k_vac*F_co2 = 0
        J[4, i_co2] = -self._k_vac;  J[4, i_wvac] = 1.0
        # r5: T_in - T_amb_default = 0
        J[5, i_T] = 1.0
        # r6: P_in - P_amb_default = 0
        J[6, i_P] = 1.0

        return LinearizedModel(
            unit_id=self.unit_id,
            variables=vnames,
            x0=x0,
            f0=f0,
            J=J,
            bounds=self.bounds(),
            objective_terms=self.objective_contribution(x0_dict),
            is_exact=True,
            trust_region=self.trust_region,
        )
